name: PR Author Stats
on:
  pull_request:
    types: [opened]

jobs:
  analyze-pr-author:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PR Analysis
        uses: actions/github-script@v7
        with:
          script: |
            const { analyzePRAndComment } = require('./scripts/analyze.js');
            await analyzePRAndComment(github, context);
